config/routes.rb
Rails.application.routes.draw do
  resources :salary_usecases
  resources :accounts
  resources :policies
  resources :gideon_tests
  resources :media_uploads
  resources :onesimus_tests
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'
  post '/salary_usecases/:id', to: 'salary_usecases#process_payment', as: 'process_payment'

end

app/models/onesimus_test.rb
class OnesimusTest < ApplicationRecord
    # has_one_attached :image
    has_many_attached :images
    has_many :media_uploads
end

app/controllers/onesimus_tests_controller.rb
class OnesimusTestsController < ApplicationController
  before_action :set_onesimus_test, only: %i[ show edit update destroy ]

  # GET /onesimus_tests or /onesimus_tests.json
  def index
    @onesimus_tests = OnesimusTest.all
  end

  # GET /onesimus_tests/1 or /onesimus_tests/1.json
  def show
  end

  # GET /onesimus_tests/new
  def new
    @onesimus_test = OnesimusTest.new
  end

  # GET /onesimus_tests/1/edit
  def edit
  end

  # POST /onesimus_tests or /onesimus_tests.json
  def create
    @onesimus_test = OnesimusTest.new(onesimus_test_params)

    respond_to do |format|
      if @onesimus_test.save
        format.html { redirect_to onesimus_test_url(@onesimus_test), notice: "Onesimus test was successfully created." }
        format.json { render :show, status: :created, location: @onesimus_test }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @onesimus_test.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /onesimus_tests/1 or /onesimus_tests/1.json
  def update
    respond_to do |format|
      if @onesimus_test.update(onesimus_test_params)
        format.html { redirect_to onesimus_test_url(@onesimus_test), notice: "Onesimus test was successfully updated." }
        format.json { render :show, status: :ok, location: @onesimus_test }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @onesimus_test.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /onesimus_tests/1 or /onesimus_tests/1.json
  def destroy
    @onesimus_test.destroy

    respond_to do |format|
      format.html { redirect_to onesimus_tests_url, notice: "Onesimus test was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_onesimus_test
      @onesimus_test = OnesimusTest.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def onesimus_test_params
      params.require(:onesimus_test).permit(:name_of_insured, :address, :occupation, :telephone, :reg_number, :make, :model, 
        :year_of_make, :business_private, :driver_name, :driver_address, :driver_age, :driver_telephone, :driving_license_no, 
        :licence_class, :date_of_issue, :convicted_of_motoring_offence, :loss_date, :time_of_loss, :accident_location, 
        :vehicle_speed, :nature_of_loss, :accident_desc, :report_date, :policy_number, :images =>[])
    end
end

app/helpers/onesimus_tests_helper.rb
module OnesimusTestsHelper
end

app/views/onesimus_tests/_form.html.erb
<%#= form_with(model: onesimus_test) do |form| %>

<div>
  <%= simple_form_for @onesimus_test do |f| %>


    <div class="row" style="width:50%; margin: 0 auto;">
      <% if onesimus_test.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(onesimus_test.errors.count, "error") %> prohibited this onesimus_test from being saved:</h2>

          <ul>
            <% onesimus_test.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="col-sm-6">
        <%= f.input :name_of_insured %>
        <%= f.input :address %>
        <%= f.input :occupation %>
        <%= f.input :telephone %>
        <%= f.input :reg_number %>
        <%= f.input :make %>
        <%= f.input :model %>
        <%= f.input :year_of_make %>
        <%= f.input :business_private %>
        <%= f.input :driver_name %>
        <%= f.input :driver_address %>
        <%= f.input :driver_age %>
        <%= f.input :driver_telephone %>
      </div>
      <div class="col-sm-6">
        <%= f.input :driving_license_no %>
        <%= f.input :licence_class %>
        <%= f.input :date_of_issue, as: :string %>
        <div style="margin: 15px 0">
          <%= f.input :convicted_of_motoring_offence %>
        </div>
        <%= f.input :loss_date, as: :string %>
        <%= f.input :time_of_loss, as: :string %>
        <%= f.input :accident_location %>
        <%= f.input :vehicle_speed %>
        <%= f.input :nature_of_loss %>
        <%= f.input :accident_desc %>
        <%= f.input :report_date, as: :string %>
        <%= f.input :policy_number %>
        <br>
        <!--<input type="file" />-->
        <%= f.file_field :images, multiple: true,input_html:{id: "avatar-upload"} %>
      </div>
        
      <div class="row" style="margin-top:40px;">
        <div>
          <%= link_to 'Back', onesimus_tests_path, class:"btn btn-md btn-outline-dark" %>
   
          <%= f.button :submit, class:"btn btn-md btn-primary"  %>
        </div>
      </div>
      
    </div>

  <% end %>
</div>





<%# end %>

app/views/onesimus_tests/edit.html.erb
<h1>Editing Onesimus Test</h1>

<%= render 'form', onesimus_test: @onesimus_test %>

<%= link_to 'Show', @onesimus_test %> |
<%= link_to 'Back', onesimus_tests_path %>

app/views/onesimus_tests/index.html.erb
<div style="width: 70%; margin: 0 auto;">


<p id="notice"><%= notice %></p>
<br><br><br>

<h1>Insurance Claims</h1>

<div class="my-content"> 
    <div class="shadow-box-no-border">
        <hr/>
        <div class="d-flex justify-content-end">
            <!--<button class="btn btn-outline-primary">Download CSV  <i class="fa fa-download"></i></button>
            <button class="btn btn-outline-primary">Search  <i class="fa fa-search"></i></button>-->

            <%= link_to new_onesimus_test_path, class:"btn btn-outline-primary float-left" do %>
                <span class="glyphicon glyphicon-plus"></span>
                New Claim
            <% end %>
        </div>
    

        <div class="table-responsive">
        <hr/>
            <table class="table table-striped table-hover">
                <thead class="bg-light">
                <tr>
                  <th>#</th>
                  <th>Name of insured</th>
                <!--<th>Address</th>
                  <th>Occupation</th>--> 
                  <th>Telephone</th>
                  <th>Reg number</th>
                  <th>Make</th>
                  <th>Model</th>
                  <th>Year of make</th>
                  <!--<th>Business private</th>
                  <th>Driver name</th>
                  <th>Driver address</th>
                  <th>Driver age</th>
                  <th>Driver telephone</th>
                  <th>Driving license no</th>
                  <th>Licence class</th>
                  <th>Date of issue</th>
                  <th>Convicted of motoring offence</th>-->
                  <th>Loss date</th>
                  <th>Time of loss</th>
                  <th>Accident location</th>
                  <!-- <th>Vehicle speed</th>
                  <th>Nature of loss</th>
                  <th>Accident desc</th>
                  <th>Report date</th>--> 
                  <th>Policy number</th>
                  <th colspan="3"></th>
                </tr>
                </thead>

                <tbody>
                <% @onesimus_tests.each_with_index do |onesimus_test, index| %>
                    <tr>
                      <td><%= index + 1 %></td>
                      <td><%= onesimus_test.name_of_insured %></td>
                      <!--<td><%#= onesimus_test.address %></td>
                      <td><%#= onesimus_test.occupation %></td>-->
                      <td><%= onesimus_test.telephone %></td>
                      <td><%= onesimus_test.reg_number %></td>
                      <td><%= onesimus_test.make %></td>
                      <td><%= onesimus_test.model %></td>
                      <td><%= onesimus_test.year_of_make %></td>
                      <!-- <td><%#= onesimus_test.business_private %></td>
                      <td><%#= onesimus_test.driver_name %></td>
                      <td><%#= onesimus_test.driver_address %></td>
                      <td><%#= onesimus_test.driver_age %></td>
                      <td><%#= onesimus_test.driver_telephone %></td>
                      <td><%#= onesimus_test.driving_license_no %></td>
                      <td><%#= onesimus_test.licence_class %></td>
                      <td><%#= onesimus_test.date_of_issue %></td>
                      <td><%#= onesimus_test.convicted_of_motoring_offence %></td>-->
                      <td><%= onesimus_test.loss_date %></td>
                      <td><%= onesimus_test.time_of_loss %></td>
                        <!--<td><%#= onesimus_test.accident_location %></td>
                      <td><%#= onesimus_test.vehicle_speed %></td>
                      <td><%#= onesimus_test.nature_of_loss %></td>
                      <td><%#= onesimus_test.accident_desc %></td>
                      <td><%#= onesimus_test.report_date %></td>-->
                      <td><%= onesimus_test.policy_number %></td>
                      <td><%= link_to 'Show', onesimus_test, class:"btn btn-outline-dark" %></td>
                      <td><%= link_to 'Edit', edit_onesimus_test_path(onesimus_test), class:"btn btn-outline-primary"  %></td>
                      <td><%= link_to 'Destroy', onesimus_test, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-outline-danger"  %></td>
                    </tr>
                <% end %>
                </tbody>
            </table>
        </div>
    </div>
</div>

app/views/onesimus_tests/new.html.erb
<div>
    <br><br><br>
    <div class="text-center">
        <h1>Claims Form</h1>
    </div>
    <br>
    <%= render 'form', onesimus_test: @onesimus_test %>
</div>

app/views/onesimus_tests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name of insured:</strong>
  <%= @onesimus_test.name_of_insured %>
</p>

<p>
  <strong>Address:</strong>
  <%= @onesimus_test.address %>
</p>

<p>
  <strong>Occupation:</strong>
  <%= @onesimus_test.occupation %>
</p>

<p>
  <strong>Telephone:</strong>
  <%= @onesimus_test.telephone %>
</p>

<p>
  <strong>Reg number:</strong>
  <%= @onesimus_test.reg_number %>
</p>

<p>
  <strong>Make:</strong>
  <%= @onesimus_test.make %>
</p>

<p>
  <strong>Model:</strong>
  <%= @onesimus_test.model %>
</p>

<p>
  <strong>Year of make:</strong>
  <%= @onesimus_test.year_of_make %>
</p>

<p>
  <strong>Business private:</strong>
  <%= @onesimus_test.business_private %>
</p>

<p>
  <strong>Driver name:</strong>
  <%= @onesimus_test.driver_name %>
</p>

<p>
  <strong>Driver address:</strong>
  <%= @onesimus_test.driver_address %>
</p>

<p>
  <strong>Driver age:</strong>
  <%= @onesimus_test.driver_age %>
</p>

<p>
  <strong>Driver telephone:</strong>
  <%= @onesimus_test.driver_telephone %>
</p>

<p>
  <strong>Driving license no:</strong>
  <%= @onesimus_test.driving_license_no %>
</p>

<p>
  <strong>Licence class:</strong>
  <%= @onesimus_test.licence_class %>
</p>

<p>
  <strong>Date of issue:</strong>
  <%= @onesimus_test.date_of_issue %>
</p>

<p>
  <strong>Convicted of motoring offence:</strong>
  <%= @onesimus_test.convicted_of_motoring_offence %>
</p>

<p>
  <strong>Loss date:</strong>
  <%= @onesimus_test.loss_date %>
</p>

<p>
  <strong>Time of loss:</strong>
  <%= @onesimus_test.time_of_loss %>
</p>

<p>
  <strong>Accident location:</strong>
  <%= @onesimus_test.accident_location %>
</p>

<p>
  <strong>Vehicle speed:</strong>
  <%= @onesimus_test.vehicle_speed %>
</p>

<p>
  <strong>Nature of loss:</strong>
  <%= @onesimus_test.nature_of_loss %>
</p>

<p>
  <strong>Accident desc:</strong>
  <%= @onesimus_test.accident_desc %>
</p>

<p>
  <strong>Report date:</strong>
  <%= @onesimus_test.report_date %>
</p>

<p>
  <strong>Policy number:</strong>
  <%= @onesimus_test.policy_number %>
</p>

<p>
  <strong></strong>
  <%= @onesimus_test.images %>
</p>

<%= link_to 'Edit', edit_onesimus_test_path(@onesimus_test) %> |
<%= link_to 'Back', onesimus_tests_path %>