config/routes.rb
Rails.application.routes.draw do
  resources :salary_usecases
  resources :accounts
  resources :policies
  resources :gideon_tests
  resources :media_uploads
  resources :onesimus_tests
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'
  post '/salary_usecases/:id', to: 'salary_usecases#process_payment', as: 'process_payment'

end

app/models/media_upload.rb
class MediaUpload < ApplicationRecord
    belongs_to :onesimus_test
end

app/controllers/media_uploads_controller.rb
class MediaUploadsController < ApplicationController
  before_action :set_media_upload, only: %i[ show edit update destroy ]

  # GET /media_uploads or /media_uploads.json
  def index
    @media_uploads = MediaUpload.all
  end

  # GET /media_uploads/1 or /media_uploads/1.json
  def show
  end

  # GET /media_uploads/new
  def new
    @media_upload = MediaUpload.new
  end

  # GET /media_uploads/1/edit
  def edit
  end

  # POST /media_uploads or /media_uploads.json
  def create
    @media_upload = MediaUpload.new(media_upload_params)

    respond_to do |format|
      if @media_upload.save
        format.html { redirect_to media_upload_url(@media_upload), notice: "Media upload was successfully created." }
        format.json { render :show, status: :created, location: @media_upload }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @media_upload.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /media_uploads/1 or /media_uploads/1.json
  def update
    respond_to do |format|
      if @media_upload.update(media_upload_params)
        format.html { redirect_to media_upload_url(@media_upload), notice: "Media upload was successfully updated." }
        format.json { render :show, status: :ok, location: @media_upload }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @media_upload.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /media_uploads/1 or /media_uploads/1.json
  def destroy
    @media_upload.destroy

    respond_to do |format|
      format.html { redirect_to media_uploads_url, notice: "Media upload was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_media_upload
      @media_upload = MediaUpload.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def media_upload_params
      params.require(:media_upload).permit(:onesimus_test_id, :image_name, :location, :active_status, :del_status)
    end
end

app/helpers/media_uploads_helper.rb
module MediaUploadsHelper
end

app/views/media_uploads/_form.html.erb
<%= form_with(model: media_upload) do |form| %>
  <% if media_upload.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(media_upload.errors.count, "error") %> prohibited this media_upload from being saved:</h2>

      <ul>
        <% media_upload.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :onesimus_test_id %>
    <%= form.number_field :onesimus_test_id %>
  </div>

  <div class="field">
    <%= form.label :image_name %>
    <%= form.text_field :image_name %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="field">
    <%= form.label :active_status %>
    <%= form.check_box :active_status %>
  </div>

  <div class="field">
    <%= form.label :del_status %>
    <%= form.check_box :del_status %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/media_uploads/edit.html.erb
<h1>Editing Media Upload</h1>

<%= render 'form', media_upload: @media_upload %>

<%= link_to 'Show', @media_upload %> |
<%= link_to 'Back', media_uploads_path %>

app/views/media_uploads/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Media Uploads</h1>

<table>
  <thead>
    <tr>
      <th>Onesimus test</th>
      <th>Image name</th>
      <th>Location</th>
      <th>Active status</th>
      <th>Del status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @media_uploads.each do |media_upload| %>
      <tr>
        <td><%= media_upload.onesimus_test_id %></td>
        <td><%= media_upload.image_name %></td>
        <td><%= media_upload.location %></td>
        <td><%= media_upload.active_status %></td>
        <td><%= media_upload.del_status %></td>
        <td><%= link_to 'Show', media_upload %></td>
        <td><%= link_to 'Edit', edit_media_upload_path(media_upload) %></td>
        <td><%= link_to 'Destroy', media_upload, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Media Upload', new_media_upload_path %>

app/views/media_uploads/new.html.erb
<h1>New Media Upload</h1>

<%= render 'form', media_upload: @media_upload %>

<%= link_to 'Back', media_uploads_path %>

app/views/media_uploads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Onesimus test:</strong>
  <%= @media_upload.onesimus_test_id %>
</p>

<p>
  <strong>Image name:</strong>
  <%= @media_upload.image_name %>
</p>

<p>
  <strong>Location:</strong>
  <%= @media_upload.location %>
</p>

<p>
  <strong>Active status:</strong>
  <%= @media_upload.active_status %>
</p>

<p>
  <strong>Del status:</strong>
  <%= @media_upload.del_status %>
</p>

<%= link_to 'Edit', edit_media_upload_path(@media_upload) %> |
<%= link_to 'Back', media_uploads_path %>