config/routes.rb
Rails.application.routes.draw do
  resources :salary_usecases
  resources :accounts
  resources :policies
  resources :gideon_tests
  resources :media_uploads
  resources :onesimus_tests
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'
  post '/salary_usecases/:id', to: 'salary_usecases#process_payment', as: 'process_payment'

end

app/models/gideon_test.rb
class GideonTest < ApplicationRecord
end

app/controllers/gideon_tests_controller.rb
class GideonTestsController < ApplicationController
  before_action :set_gideon_test, only: %i[ show edit update destroy ]

  # GET /gideon_tests or /gideon_tests.json
  def index
    @gideon_tests = GideonTest.all
  end

  # GET /gideon_tests/1 or /gideon_tests/1.json
  def show
  end

  # GET /gideon_tests/new
  def new
    @gideon_test = GideonTest.new
  end

  # GET /gideon_tests/1/edit
  def edit
  end

  # POST /gideon_tests or /gideon_tests.json
  def create
    @gideon_test = GideonTest.new(gideon_test_params)

    respond_to do |format|
      if @gideon_test.save
        format.html { redirect_to gideon_test_url(@gideon_test), notice: "Gideon test was successfully created." }
        format.json { render :show, status: :created, location: @gideon_test }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @gideon_test.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gideon_tests/1 or /gideon_tests/1.json
  def update
    respond_to do |format|
      if @gideon_test.update(gideon_test_params)
        format.html { redirect_to gideon_test_url(@gideon_test), notice: "Gideon test was successfully updated." }
        format.json { render :show, status: :ok, location: @gideon_test }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @gideon_test.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gideon_tests/1 or /gideon_tests/1.json
  def destroy
    @gideon_test.destroy

    respond_to do |format|
      format.html { redirect_to gideon_tests_url, notice: "Gideon test was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gideon_test
      @gideon_test = GideonTest.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def gideon_test_params
      params.require(:gideon_test).permit(:first_name, :last_name, :dob, :nationality, :phone_number, :email, :id_type, :id_number, 
        :home_address, :second_address, :occupation, :gender, :new_email, :new_password)
    end
end

app/helpers/gideon_tests_helper.rb
module GideonTestsHelper
end

app/views/gideon_tests/_form.html.erb
<%= simple_form_for(@gideon_test) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  
  <div class="row" style="width:50%; margin: 0 auto;">
    <div class="col-sm-6">
      <%= f.input :first_name, input_html:{id:"fname"} %>
      <%= f.input :last_name, input_html:{id:"lname"}  %>
      <%= f.input :dob, input_html:{id:"dob"} %>
      <%= f.input :nationality, input_html:{id:"nation"}  %>
      <%= f.input :phone_number, input_html:{id:"phone"} %>
      <%= f.input :email, input_html:{id:"email"}  %>
      <%= f.input :id_type, input_html:{id:"idtype"}  %>
    </div>
    <div class="col-sm-6">
      <%= f.input :id_number, input_html:{id:"idnum"}  %>
      <%= f.input :home_address , input_html:{id:"addy"} %>
      <%= f.input :second_address, input_html:{id:"addy2"}  %>
      <%= f.input :occupation, input_html:{id:"work"} %>
      <%= f.input :gender, input_html:{id:"gender" } %>  
      <%= f.input :new_email, input_html:{id:"nemail"}  %>
      <%= f.input :new_password, input_html:{id:"npwd"}  %>
    </div>

    <div class="row" style="margin-top:40px;">
      <div>
        <%= link_to 'Back', gideon_tests_path, class:"btn btn-md btn-outline-dark" %>
        <%= f.button :submit, class:"btn btn-md btn-primary"  %>
      </div>
    </div>
  </div>
<% end %>

app/views/gideon_tests/edit.html.erb
<h1>Editing Gideon Test</h1>

<%= render 'form', gideon_test: @gideon_test %>

<%= link_to 'Show', @gideon_test %> |
<%= link_to 'Back', gideon_tests_path %>

app/views/gideon_tests/index.html.erb
<div style="width: 70%; margin: 0 auto;">


<p id="notice"><%= notice %></p>
<br><br><br>

<h1>Customer Information</h1>

<div class="my-content"> 
    <div class="shadow-box-no-border">
        <hr/>
        <div class="d-flex justify-content-end">
            <!--<button class="btn btn-outline-primary">Download CSV  <i class="fa fa-download"></i></button>
            <button class="btn btn-outline-primary">Search  <i class="fa fa-search"></i></button>-->

            <%= link_to new_gideon_test_path, class:"btn btn-outline-primary float-left" do %>
                <span class="glyphicon glyphicon-plus"></span>
                New Customer
            <% end %>
        </div>
    

        <div class="table-responsive">
        <hr/>
            <table class="table table-striped table-hover">
                <thead class="bg-light">
                  <th>#</th>
                  <th>First name</th>
                  <th>Last name</th>
                  <th>Dob</th>
                  <th>Nationality</th>
                  <th>Phone number</th>
                  <th>Email</th>
                  <th>Id type</th>
                <!--<th>Id number</th>
                  <th>Home address</th>
                  <th>Second address</th>
                  <th>Occupation</th>
                  <th>Gender</th>-->  
                  <th colspan="3"></th>
                </thead>

                <tbody>
                <% @gideon_tests.each_with_index do |gideon_test, index| %>
                    <tr>
                      <td><%= index + 1 %></td>
                      <td><%= gideon_test.first_name %></td>
                      <td><%= gideon_test.last_name %></td>
                      <td><%= gideon_test.dob %></td>
                      <td><%= gideon_test.nationality %></td>
                      <td><%= gideon_test.phone_number %></td>
                      <td><%= gideon_test.email %></td>
                      <td><%= gideon_test.id_type %></td>
                      <!--<td><%#= gideon_test.id_number %></td>
                      <td><%#= gideon_test.home_address %></td>
                      <td><%#= gideon_test.second_address %></td>
                      <td><%#= gideon_test.occupation %></td>
                      <td><%#= gideon_test.gender %></td>-->
                      <td><%= link_to 'Show', gideon_test, class:"btn btn-outline-dark"  %></td>
                      <td><%= link_to 'Edit', edit_gideon_test_path(gideon_test), class:"btn btn-outline-primary"  %></td>
                      <td><%= link_to 'Destroy', gideon_test, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-outline-danger" %></td>
                    </tr>
                <% end %>
                </tbody>
            </table>
        </div>
    </div>
</div>

app/views/gideon_tests/new.html.erb
<div>
    <br><br><br>
    <div class="text-center">
        <h1>Customer Information Form</h1>
    </div>
    <br>
   <%= render 'form', gideon_test: @gideon_test %>
</div>

app/views/gideon_tests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @gideon_test.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @gideon_test.last_name %>
</p>

<p>
  <strong>Dob:</strong>
  <%= @gideon_test.dob %>
</p>

<p>
  <strong>Nationality:</strong>
  <%= @gideon_test.nationality %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @gideon_test.phone_number %>
</p>

<p>
  <strong>Email:</strong>
  <%= @gideon_test.email %>
</p>

<p>
  <strong>Id type:</strong>
  <%= @gideon_test.id_type %>
</p>

<p>
  <strong>Id number:</strong>
  <%= @gideon_test.id_number %>
</p>

<p>
  <strong>Home address:</strong>
  <%= @gideon_test.home_address %>
</p>

<p>
  <strong>Second address:</strong>
  <%= @gideon_test.second_address %>
</p>

<p>
  <strong>Occupation:</strong>
  <%= @gideon_test.occupation %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @gideon_test.gender %>
</p>

<%= link_to 'Edit', edit_gideon_test_path(@gideon_test) %> |
<%= link_to 'Back', gideon_tests_path %>