config/routes.rb
Rails.application.routes.draw do
  resources :salary_usecases
  resources :accounts
  resources :policies
  resources :gideon_tests
  resources :media_uploads
  resources :onesimus_tests
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'
  post '/salary_usecases/:id', to: 'salary_usecases#process_payment', as: 'process_payment'

end

app/models/account.rb
class Account < ApplicationRecord
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: %i[ show edit update destroy ]

  # GET /accounts or /accounts.json
  def index
    # @accounts = Account.all
    if params[:filter].present?
      search_str=""
      search_arr=[]

      filter_params = params[:filter]

      @account_no = filter_params["account_no"]
    


      if @account_no.present?
        f_str = @account_no
        f_str = f_str.gsub("'","''")
        search_arr << "account_number iLike '#{f_str}' "
        # search_arr << "account_no iLIKE '#{@account_no}' "
      end

      logger.info "+++++++++++++++++++++++++++++++"
      logger.info search_arr.inspect

      search_str << search_arr.join(" and ")

      if !search_str.present?
        @accounts = Account.all
      else
        @accounts = Account.where(search_str).order(created_at: :desc)
        logger.info "THIS IS THE Account NUMBER WE ARE LOOKING FOR === #{@accounts.inspect} === "
      end

    else
      @accounts = Account.all
    end
  end

  # GET /accounts/1 or /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts or /accounts.json
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to account_url(@account), notice: "Account was successfully created." }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1 or /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to account_url(@account), notice: "Account was successfully updated." }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1 or /accounts/1.json
  # def destroy
  #   @account.destroy

  #   respond_to do |format|
  #     format.html { redirect_to accounts_url, notice: "Account was successfully destroyed." }
  #     format.json { head :no_content }
  #   end
  # end

  def destroy
    if @account.active_status
      @account.active_status = false
      @account.save(validate: false)
      respond_to do |format|
        format.html { redirect_to accounts_url, notice: "Account was successfully closed." }
        format.json { head :no_content }
      end
    else
      @account.active_status = true
      @account.save(validate: false)
      respond_to do |format|
        format.html { redirect_to accounts_url, notice: "Account was successfully reopened." }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def account_params
      params.require(:account).permit(:account_name, :account_number, :branch, :active_status, :del_status)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_form.html.erb
<%= simple_form_for(@account) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  <div class="row" style="width:50%; margin: 0 auto;">
    <div>
      <div class="form-inputs">
        <%= f.input :account_name %>
        <%= f.input :account_number %>
        <%= f.input :branch %>
        <%= f.input :active_status, input_html:{checked: "checked"}, as: :hidden %>
        <%= f.input :del_status, as: :hidden  %>

        <br>
       
      </div>

      <div class="row" style="margin-top:40px;">
        <div>
          <%= link_to 'Back', accounts_path, class:"btn btn-md btn-outline-dark" %>
          <%= f.button :submit, class:"btn btn-md btn-primary"  %>
        </div>
      </div>
    </div>
   
  </div>

<% end %>

app/views/accounts/edit.html.erb
<h1>Editing Account</h1>

<%= render 'form', account: @account %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<div style="width: 70%; margin: 0 auto;">
  <p id="notice"><%= notice %></p>
  <br><br><br>

  <h1>Account Management</h1>

  <div class="my-content"> 
    <div class="shadow-box-no-border">
        <hr/>
        <div class="d-flex justify-content-between">
            <div class="left">
             
              <%= simple_form_for :filter, url: accounts_path, :method =>'get' ,html: { class: 'form-horizontal' } do |f| %>
                <div>
                  
                  <input type="text" name="filter[account_no]" id="id1" placeholder="Search By Account No."/>
                  <%= f.submit "Search", class: "btn btn-md btn-secondary",:data => {:disable_with => 'Search'} %>
                </div>
              <% end %>
            </div>

            <div>
              <%= link_to 'Refresh', accounts_path, class:"btn btn-dark "%>
            </div>

            <%= link_to new_account_path, class:"btn btn-outline-primary float-left" do %>
                <span class="glyphicon glyphicon-plus"></span>
                Create Account
            <% end %>  
        </div>
    

        <div class="table-responsive">
        <hr/>
            <table class="table table-striped table-hover">
                <thead class="bg-light">
                  <th>#</th>
                  <th>Account Number</th>
                  <th>Account Name</th>
                  <th>Branch</th>
                  <th>Status</th>
                  <th colspan="3"></th>
                </thead>

                <tbody>
                <% @accounts.each_with_index do |account, index| %>
                    <tr>
                      <td><%= index + 1 %></td>
                      <td><%= account.account_name %></td>
                      <td><%= account.account_number %></td>
                      <td><%= account.branch %></td>
                      <td>
                        <% if account.active_status %>
                          Active  
                        <% else %>
                          Closed  
                        <% end %>
                      </td>
                      <td>
                        <% if account.active_status %>
                          <%= link_to 'Close Account?', account, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-outline-danger" %>
                        <% else %>
                          <%= link_to 'Reopen Account?', account, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-outline-success" %>
                        <% end %>
                      </td>
                      <td><%= link_to 'Show', account, class:"btn btn-outline-dark"  %></td>
                      <td><%= link_to 'Edit', edit_account_path(account), class:"btn btn-outline-primary"  %></td>
                    </tr>
                <% end %>
                </tbody>
            </table>
        </div>
    </div>
</div>

app/views/accounts/new.html.erb
<div>
    <br><br><br>
    <div class="text-center">
        <h1>Account Form</h1>
    </div>
    <br>
   <%= render 'form', account: @account %>
</div>

app/views/accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Account name:</strong>
  <%= @account.account_name %>
</p>

<p>
  <strong>Account number:</strong>
  <%= @account.account_number %>
</p>

<p>
  <strong>Branch:</strong>
  <%= @account.branch %>
</p>

<p>
  <strong>Active status:</strong>
  <%= @account.active_status %>
</p>

<p>
  <strong>Del status:</strong>
  <%= @account.del_status %>
</p>

<%= link_to 'Edit', edit_account_path(@account) %> |
<%= link_to 'Back', accounts_path %>